// Lista completa de países (ISO 3166-1 alpha-2), nomes em português, para o
// seletor de país no onboarding e em Perfil. A base nutricional (TACO) hoje é
// só brasileira (ver food_matcher._COMMON_DEFAULT_BR), o campo já fica
// disponível pra todo mundo pensando numa base equivalente futura por país.
const RAW: { id: string; label: string }[] = [
  { id: "AF", label: "Afeganistão" },
  { id: "ZA", label: "África do Sul" },
  { id: "AL", label: "Albânia" },
  { id: "DE", label: "Alemanha" },
  { id: "AD", label: "Andorra" },
  { id: "AO", label: "Angola" },
  { id: "AI", label: "Anguilla" },
  { id: "AQ", label: "Antártida" },
  { id: "AG", label: "Antígua e Barbuda" },
  { id: "SA", label: "Arábia Saudita" },
  { id: "DZ", label: "Argélia" },
  { id: "AR", label: "Argentina" },
  { id: "AM", label: "Armênia" },
  { id: "AW", label: "Aruba" },
  { id: "AU", label: "Austrália" },
  { id: "AT", label: "Áustria" },
  { id: "AZ", label: "Azerbaijão" },
  { id: "BS", label: "Bahamas" },
  { id: "BH", label: "Bahrein" },
  { id: "BD", label: "Bangladesh" },
  { id: "BB", label: "Barbados" },
  { id: "BE", label: "Bélgica" },
  { id: "BZ", label: "Belize" },
  { id: "BJ", label: "Benin" },
  { id: "BY", label: "Bielorrússia" },
  { id: "BO", label: "Bolívia" },
  { id: "BA", label: "Bósnia e Herzegovina" },
  { id: "BW", label: "Botsuana" },
  { id: "BR", label: "Brasil" },
  { id: "BN", label: "Brunei" },
  { id: "BG", label: "Bulgária" },
  { id: "BF", label: "Burkina Faso" },
  { id: "BI", label: "Burundi" },
  { id: "BT", label: "Butão" },
  { id: "CV", label: "Cabo Verde" },
  { id: "CM", label: "Camarões" },
  { id: "KH", label: "Camboja" },
  { id: "CA", label: "Canadá" },
  { id: "QA", label: "Catar" },
  { id: "KZ", label: "Cazaquistão" },
  { id: "TD", label: "Chade" },
  { id: "CL", label: "Chile" },
  { id: "CN", label: "China" },
  { id: "CY", label: "Chipre" },
  { id: "CO", label: "Colômbia" },
  { id: "KM", label: "Comores" },
  { id: "CG", label: "Congo" },
  { id: "CD", label: "Congo (RD)" },
  { id: "KP", label: "Coreia do Norte" },
  { id: "KR", label: "Coreia do Sul" },
  { id: "CI", label: "Costa do Marfim" },
  { id: "CR", label: "Costa Rica" },
  { id: "HR", label: "Croácia" },
  { id: "CU", label: "Cuba" },
  { id: "DK", label: "Dinamarca" },
  { id: "DJ", label: "Djibuti" },
  { id: "DM", label: "Dominica" },
  { id: "EG", label: "Egito" },
  { id: "SV", label: "El Salvador" },
  { id: "AE", label: "Emirados Árabes Unidos" },
  { id: "EC", label: "Equador" },
  { id: "ER", label: "Eritreia" },
  { id: "SK", label: "Eslováquia" },
  { id: "SI", label: "Eslovênia" },
  { id: "ES", label: "Espanha" },
  { id: "US", label: "Estados Unidos" },
  { id: "EE", label: "Estônia" },
  { id: "SZ", label: "Essuatíni" },
  { id: "ET", label: "Etiópia" },
  { id: "FJ", label: "Fiji" },
  { id: "PH", label: "Filipinas" },
  { id: "FI", label: "Finlândia" },
  { id: "FR", label: "França" },
  { id: "GA", label: "Gabão" },
  { id: "GM", label: "Gâmbia" },
  { id: "GH", label: "Gana" },
  { id: "GE", label: "Geórgia" },
  { id: "GI", label: "Gibraltar" },
  { id: "GR", label: "Grécia" },
  { id: "GD", label: "Granada" },
  { id: "GL", label: "Groenlândia" },
  { id: "GP", label: "Guadalupe" },
  { id: "GU", label: "Guam" },
  { id: "GT", label: "Guatemala" },
  { id: "GY", label: "Guiana" },
  { id: "GF", label: "Guiana Francesa" },
  { id: "GN", label: "Guiné" },
  { id: "GQ", label: "Guiné Equatorial" },
  { id: "GW", label: "Guiné-Bissau" },
  { id: "HT", label: "Haiti" },
  { id: "HN", label: "Honduras" },
  { id: "HK", label: "Hong Kong" },
  { id: "HU", label: "Hungria" },
  { id: "YE", label: "Iêmen" },
  { id: "IN", label: "Índia" },
  { id: "ID", label: "Indonésia" },
  { id: "IR", label: "Irã" },
  { id: "IQ", label: "Iraque" },
  { id: "IE", label: "Irlanda" },
  { id: "IS", label: "Islândia" },
  { id: "IL", label: "Israel" },
  { id: "IT", label: "Itália" },
  { id: "JM", label: "Jamaica" },
  { id: "JP", label: "Japão" },
  { id: "JO", label: "Jordânia" },
  { id: "KI", label: "Kiribati" },
  { id: "KW", label: "Kuwait" },
  { id: "LA", label: "Laos" },
  { id: "LS", label: "Lesoto" },
  { id: "LV", label: "Letônia" },
  { id: "LB", label: "Líbano" },
  { id: "LR", label: "Libéria" },
  { id: "LY", label: "Líbia" },
  { id: "LI", label: "Liechtenstein" },
  { id: "LT", label: "Lituânia" },
  { id: "LU", label: "Luxemburgo" },
  { id: "MO", label: "Macau" },
  { id: "MK", label: "Macedônia do Norte" },
  { id: "MG", label: "Madagascar" },
  { id: "MY", label: "Malásia" },
  { id: "MW", label: "Malawi" },
  { id: "MV", label: "Maldivas" },
  { id: "ML", label: "Mali" },
  { id: "MT", label: "Malta" },
  { id: "MA", label: "Marrocos" },
  { id: "MQ", label: "Martinica" },
  { id: "MU", label: "Maurício" },
  { id: "MR", label: "Mauritânia" },
  { id: "YT", label: "Mayotte" },
  { id: "MX", label: "México" },
  { id: "MM", label: "Mianmar" },
  { id: "FM", label: "Micronésia" },
  { id: "MZ", label: "Moçambique" },
  { id: "MD", label: "Moldávia" },
  { id: "MC", label: "Mônaco" },
  { id: "MN", label: "Mongólia" },
  { id: "ME", label: "Montenegro" },
  { id: "NA", label: "Namíbia" },
  { id: "NR", label: "Nauru" },
  { id: "NP", label: "Nepal" },
  { id: "NI", label: "Nicarágua" },
  { id: "NE", label: "Níger" },
  { id: "NG", label: "Nigéria" },
  { id: "NO", label: "Noruega" },
  { id: "NC", label: "Nova Caledônia" },
  { id: "NZ", label: "Nova Zelândia" },
  { id: "OM", label: "Omã" },
  { id: "NL", label: "Países Baixos" },
  { id: "PW", label: "Palau" },
  { id: "PS", label: "Palestina" },
  { id: "PA", label: "Panamá" },
  { id: "PG", label: "Papua-Nova Guiné" },
  { id: "PK", label: "Paquistão" },
  { id: "PY", label: "Paraguai" },
  { id: "PE", label: "Peru" },
  { id: "PF", label: "Polinésia Francesa" },
  { id: "PL", label: "Polônia" },
  { id: "PR", label: "Porto Rico" },
  { id: "PT", label: "Portugal" },
  { id: "KE", label: "Quênia" },
  { id: "KG", label: "Quirguistão" },
  { id: "GB", label: "Reino Unido" },
  { id: "CF", label: "República Centro-Africana" },
  { id: "CZ", label: "República Tcheca" },
  { id: "DO", label: "República Dominicana" },
  { id: "RE", label: "Reunião" },
  { id: "RO", label: "Romênia" },
  { id: "RW", label: "Ruanda" },
  { id: "RU", label: "Rússia" },
  { id: "EH", label: "Saara Ocidental" },
  { id: "WS", label: "Samoa" },
  { id: "AS", label: "Samoa Americana" },
  { id: "SM", label: "San Marino" },
  { id: "SH", label: "Santa Helena" },
  { id: "LC", label: "Santa Lúcia" },
  { id: "KN", label: "São Cristóvão e Névis" },
  { id: "ST", label: "São Tomé e Príncipe" },
  { id: "VC", label: "São Vicente e Granadinas" },
  { id: "SN", label: "Senegal" },
  { id: "SL", label: "Serra Leoa" },
  { id: "RS", label: "Sérvia" },
  { id: "SC", label: "Seicheles" },
  { id: "SG", label: "Singapura" },
  { id: "SY", label: "Síria" },
  { id: "SO", label: "Somália" },
  { id: "LK", label: "Sri Lanka" },
  { id: "SD", label: "Sudão" },
  { id: "SS", label: "Sudão do Sul" },
  { id: "SE", label: "Suécia" },
  { id: "CH", label: "Suíça" },
  { id: "SR", label: "Suriname" },
  { id: "TH", label: "Tailândia" },
  { id: "TW", label: "Taiwan" },
  { id: "TJ", label: "Tajiquistão" },
  { id: "TZ", label: "Tanzânia" },
  { id: "TL", label: "Timor-Leste" },
  { id: "TG", label: "Togo" },
  { id: "TO", label: "Tonga" },
  { id: "TT", label: "Trinidad e Tobago" },
  { id: "TN", label: "Tunísia" },
  { id: "TM", label: "Turcomenistão" },
  { id: "TR", label: "Turquia" },
  { id: "TV", label: "Tuvalu" },
  { id: "UA", label: "Ucrânia" },
  { id: "UG", label: "Uganda" },
  { id: "UY", label: "Uruguai" },
  { id: "UZ", label: "Uzbequistão" },
  { id: "VU", label: "Vanuatu" },
  { id: "VA", label: "Vaticano" },
  { id: "VE", label: "Venezuela" },
  { id: "VN", label: "Vietnã" },
  { id: "ZM", label: "Zâmbia" },
  { id: "ZW", label: "Zimbábue" },
  { id: "ZZ", label: "Outro" },
];

// "Outro" sempre por último, o resto em ordem alfabética (localeCompare
// pt-BR trata acentos corretamente: "Áustria" fica com os "A", não no fim).
export const COUNTRY_OPTIONS: { id: string; label: string }[] = [
  ...RAW.filter((c) => c.id !== "ZZ").sort((a, b) => a.label.localeCompare(b.label, "pt-BR")),
  ...RAW.filter((c) => c.id === "ZZ"),
];
